/**
 * Uninstall OTP Management Page
 * Admins enter a device UUID to generate or retrieve the active OTP for
 * that device. The full OTP list (all devices) is displayed below.
 */
import { useState, useEffect } from 'react';
import { Copy, RefreshCw, Clock, Search, CheckCircle, X } from 'lucide-react';
import { MainLayout } from '../../components/Layout';
import { Card, Table, Badge, Button, Input } from '../../components/Common';
import { formatDateTime } from '../../utils/helpers';
import useOtp from '../../hooks/useOtp';

function UninstallOTP() {
  const { otpList, otpSummary, currentOtp, loading, error, generating, fetchCurrentOtp, generateOtp } =
    useOtp();

  const [deviceId, setDeviceId] = useState('');
  const [copied, setCopied] = useState(false);
  const [notification, setNotification] = useState(null);

  // ─── Auto-dismiss notification ────────────────────────────────────────────
  useEffect(() => {
    if (!notification) return;
    const t = setTimeout(() => setNotification(null), 4000);
    return () => clearTimeout(t);
  }, [notification]);

  const handleFetchCurrentOtp = async () => {
    if (!deviceId.trim()) return;
    await fetchCurrentOtp(deviceId.trim());
  };

  const handleGenerateOtp = async () => {
    if (!deviceId.trim()) {
      setNotification({ type: 'error', message: 'Please enter a Device UUID first' });
      return;
    }
    const result = await generateOtp(deviceId.trim());
    if (!result.success) {
      setNotification({ type: 'error', message: result.error });
    }
  };

  const handleCopyOtp = () => {
    const code = currentOtp?.otp_code ?? currentOtp?.otp ?? '';
    if (!code) return;
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const otpCode = currentOtp?.otp_code ?? currentOtp?.otp ?? null;
  const otpExpiry = currentOtp?.expires_at ?? currentOtp?.expiry ?? null;

  const historyColumns = [
    {
      key: 'otp_code',
      label: 'OTP Code',
      render: (row) => (
        <span className="font-mono font-semibold tracking-widest">
          {row.otp_code ?? row.otp ?? '—'}
        </span>
      ),
    },
    {
      key: 'device_id',
      label: 'Device ID',
      render: (row) => row.device_id ?? row.device?.id ?? '—',
    },
    {
      key: 'generated_by',
      label: 'Generated By',
      render: (row) => row.generated_by?.username ?? row.admin?.username ?? '—',
    },
    {
      key: 'created_at',
      label: 'Generated At',
      render: (row) => formatDateTime(row.created_at ?? row.generated_at),
    },
    {
      key: 'used_at',
      label: 'Used At',
      render: (row) =>
        row.used_at ? (
          formatDateTime(row.used_at)
        ) : (
          <span className="text-gray-400">—</span>
        ),
    },
    {
      key: 'status',
      label: 'Status',
      render: (row) => {
        const variants = { used: 'success', expired: 'danger', pending: 'warning' };
        return (
          <Badge variant={variants[row.status] ?? 'default'}>
            {row.status ?? '—'}
          </Badge>
        );
      },
    },
  ];

  return (
    <MainLayout title="Uninstall OTP Management">

      {/* Notification */}
      {notification && (
        <div
          className={`mb-4 p-3 rounded-lg flex items-center justify-between text-sm ${
            notification.type === 'success'
              ? 'bg-green-50 border border-green-200 text-green-700'
              : 'bg-red-50 border border-red-200 text-red-700'
          }`}
        >
          {notification.message}
          <button onClick={() => setNotification(null)} className="ml-4 hover:opacity-70">
            <X size={14} />
          </button>
        </div>
      )}

      {/* OTP Generator Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <Card className="lg:col-span-2">
          {/* Device ID input */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Device UUID
            </label>
            <div className="flex gap-2">
              <Input
                placeholder="Enter device UUID to generate / view OTP…"
                prefix={<Search size={18} />}
                value={deviceId}
                onChange={(e) => setDeviceId(e.target.value)}
                containerClassName="flex-1"
              />
              <Button variant="outline" onClick={handleFetchCurrentOtp} disabled={!deviceId.trim()}>
                Fetch OTP
              </Button>
            </div>
          </div>

          {/* OTP Display */}
          <div className="text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Current OTP</h3>
            <div className="bg-gradient-to-r from-blue-50 to-slate-50 rounded-lg p-8 mb-6 border-2 border-dashed border-blue-200">
              {otpCode ? (
                <>
                  <p className="text-6xl font-bold tracking-widest text-blue-800 font-mono">
                    {otpCode}
                  </p>
                  {otpExpiry && (
                    <p className="text-sm text-gray-600 mt-4">
                      Expires: {formatDateTime(otpExpiry)}
                    </p>
                  )}
                </>
              ) : (
                <p className="text-gray-400 text-lg">
                  {deviceId
                    ? 'No active OTP — generate one or fetch current'
                    : 'Enter a Device UUID above'}
                </p>
              )}
            </div>

            <div className="flex gap-3 justify-center">
              <Button
                variant="primary"
                onClick={handleCopyOtp}
                className="gap-2"
                disabled={!otpCode}
              >
                {copied ? <CheckCircle size={18} /> : <Copy size={18} />}
                {copied ? 'Copied!' : 'Copy OTP'}
              </Button>
              <Button
                variant="secondary"
                onClick={handleGenerateOtp}
                isLoading={generating}
                className="gap-2"
              >
                <RefreshCw size={18} />
                Generate New OTP
              </Button>
            </div>
          </div>
        </Card>

        {/* OTP Info Card */}
        <Card title="OTP Information">
          <div className="space-y-4 text-sm">
            <div className="p-3 bg-blue-50 rounded-lg">
              <p className="text-gray-600 mb-1">Valid Duration</p>
              <p className="text-lg font-semibold text-blue-800">5 Minutes</p>
            </div>
            <div className="p-3 bg-green-50 rounded-lg">
              <p className="text-gray-600 mb-1">Usage</p>
              <p className="text-lg font-semibold text-green-800">Single Use</p>
            </div>
            <div className="p-3 bg-amber-50 rounded-lg">
              <p className="text-gray-600 mb-1">Max Attempts</p>
              <p className="text-lg font-semibold text-amber-800">3 Attempts</p>
            </div>
            <div className="p-3 bg-purple-50 rounded-lg">
              <p className="text-gray-600 mb-1">Format</p>
              <p className="text-lg font-semibold text-purple-800">8 Digits</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Error state */}
      {error && (
        <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
          {error}
        </div>
      )}

      {/* All OTPs History */}
      <Card
        title="OTP History"
        subtitle="All generated OTPs across all devices"
        className="mt-8"
      >
        {loading ? (
          <div className="py-12 text-center text-gray-400">Loading OTP history…</div>
        ) : otpList.length === 0 ? (
          <div className="py-12 text-center text-gray-400">No OTPs found</div>
        ) : (
          <Table columns={historyColumns} data={otpList} />
        )}
      </Card>

      {/* Summary Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mt-8">
        <Card>
          <div className="text-center">
            <Clock size={32} className="text-blue-600 mx-auto mb-2" />
            <p className="text-gray-600 text-sm mb-2">Total Generated</p>
            <p className="text-3xl font-bold">{otpSummary.total}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-2">Pending</p>
            <p className="text-3xl font-bold text-amber-600">{otpSummary.pending}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-2">Used</p>
            <p className="text-3xl font-bold text-green-600">{otpSummary.used}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-2">Expired</p>
            <p className="text-3xl font-bold text-red-600">{otpSummary.expired}</p>
          </div>
        </Card>
      </div>
    </MainLayout>
  );
}

export default UninstallOTP;
