/**
 * Uninstall OTP Page
 * Display and manage OTP for uninstalling the MDM app
 */
import { useState } from 'react';
import { Copy, RefreshCw, Clock } from 'lucide-react';
import { MainLayout } from '../../components/Layout';
import { Card, Table, Badge, Button } from '../../components/Common';
import { formatDateTime } from '../../utils/helpers';

function UninstallOTP() {
  const [currentOTP, setCurrentOTP] = useState('562847');
  const [otpExpiresIn, setOtpExpiresIn] = useState('expires in 5 mins');
  const [copied, setCopied] = useState(false);

  const [otpHistory] = useState([
    {
      id: 1,
      otp: '384921',
      generatedBy: 'John Doe',
      generatedAt: new Date(Date.now() - 60 * 60000),
      usedAt: new Date(Date.now() - 55 * 60000),
      status: 'used',
      deviceId: 'DEV-001',
    },
    {
      id: 2,
      otp: '127654',
      generatedBy: 'Jane Smith',
      generatedAt: new Date(Date.now() - 120 * 60000),
      usedAt: new Date(Date.now() - 115 * 60000),
      status: 'used',
      deviceId: 'DEV-002',
    },
    {
      id: 3,
      otp: '938461',
      generatedBy: 'Mike Johnson',
      generatedAt: new Date(Date.now() - 180 * 60000),
      usedAt: null,
      status: 'expired',
      deviceId: 'DEV-003',
    },
    {
      id: 4,
      otp: '456789',
      generatedBy: 'Sarah Wilson',
      generatedAt: new Date(Date.now() - 240 * 60000),
      usedAt: new Date(Date.now() - 235 * 60000),
      status: 'used',
      deviceId: 'DEV-004',
    },
    {
      id: 5,
      otp: '789123',
      generatedBy: 'Tom Brown',
      generatedAt: new Date(Date.now() - 300 * 60000),
      usedAt: null,
      status: 'expired',
      deviceId: 'DEV-005',
    },
  ]);

  const handleCopyOTP = () => {
    navigator.clipboard.writeText(currentOTP);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateNewOTP = () => {
    // Generate random 6-digit OTP
    const newOTP = Math.floor(100000 + Math.random() * 900000).toString();
    setCurrentOTP(newOTP);
    setOtpExpiresIn('expires in 10 mins');
  };

  const historyColumns = [
    { key: 'otp', label: 'OTP Code' },
    { key: 'generatedBy', label: 'Generated By' },
    {
      key: 'generatedAt',
      label: 'Generated At',
      render: (row) => formatDateTime(row.generatedAt),
    },
    {
      key: 'usedAt',
      label: 'Used At',
      render: (row) =>
        row.usedAt ? formatDateTime(row.usedAt) : <span className="text-gray-400">-</span>,
    },
    {
      key: 'deviceId',
      label: 'Device ID',
    },
    {
      key: 'status',
      label: 'Status',
      render: (row) => {
        const variants = {
          used: 'success',
          expired: 'danger',
          pending: 'warning',
        };
        return <Badge variant={variants[row.status]}>{row.status}</Badge>;
      },
    },
  ];

  return (
    <MainLayout title="Uninstall OTP Management">
      {/* Current OTP Card */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <Card className="lg:col-span-2">
          <div className="text-center">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Current OTP</h3>

            {/* OTP Display */}
            <div className="bg-gradient-to-r from-blue-50 to-slate-50 rounded-lg p-8 mb-6 border-2 border-dashed border-blue-200">
              <p className="text-6xl font-bold tracking-widest text-blue-800 font-mono">
                {currentOTP}
              </p>
              <p className="text-sm text-gray-600 mt-4">{otpExpiresIn}</p>
            </div>

            {/* Actions */}
            <div className="flex gap-3 justify-center">
              <Button
                variant="primary"
                onClick={handleCopyOTP}
                className="gap-2"
              >
                <Copy size={18} />
                {copied ? 'Copied!' : 'Copy OTP'}
              </Button>
              <Button
                variant="secondary"
                onClick={handleGenerateNewOTP}
                className="gap-2"
              >
                <RefreshCw size={18} />
                Generate New
              </Button>
            </div>
          </div>
        </Card>

        {/* OTP Info Card */}
        <Card title="OTP Information">
          <div className="space-y-4 text-sm">
            <div className="p-3 bg-blue-50 rounded-lg">
              <p className="text-gray-600 mb-1">Valid Duration</p>
              <p className="text-lg font-semibold text-blue-800">10 Minutes</p>
            </div>
            <div className="p-3 bg-green-50 rounded-lg">
              <p className="text-gray-600 mb-1">Usage</p>
              <p className="text-lg font-semibold text-green-800">Single Use</p>
            </div>
            <div className="p-3 bg-amber-50 rounded-lg">
              <p className="text-gray-600 mb-1">Purpose</p>
              <p className="text-lg font-semibold text-amber-800">App Uninstall</p>
            </div>
            <div className="p-3 bg-purple-50 rounded-lg">
              <p className="text-gray-600 mb-1">Format</p>
              <p className="text-lg font-semibold text-purple-800">6 Digits</p>
            </div>
          </div>
        </Card>
      </div>

      {/* OTP History */}
      <Card
        title="OTP History"
        subtitle="List of all generated OTPs and their usage status"
        className="mt-8"
      >
        <Table columns={historyColumns} data={otpHistory} />
      </Card>

      {/* Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
        <Card>
          <div className="text-center">
            <Clock size={32} className="text-blue-600 mx-auto mb-2" />
            <p className="text-gray-600 text-sm mb-2">Total OTPs Generated</p>
            <p className="text-3xl font-bold">{otpHistory.length}</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-2">OTPs Used</p>
            <p className="text-3xl font-bold text-green-600">
              {otpHistory.filter((o) => o.status === 'used').length}
            </p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-2">OTPs Expired</p>
            <p className="text-3xl font-bold text-red-600">
              {otpHistory.filter((o) => o.status === 'expired').length}
            </p>
          </div>
        </Card>
      </div>
    </MainLayout>
  );
}

export default UninstallOTP;
